version: '3.5'

services:
  boilerplatejs_ssl:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.9.1
    restart: always
    volumes:
      - ${HTTP_VOLUME:-/tmp/nginx}/conf.d:/etc/nginx/conf.d
      - ${HTTP_VOLUME:-/tmp/nginx}/vhost.d:/etc/nginx/vhost.d
      - ${HTTP_VOLUME:-/tmp/nginx}/html:/usr/share/nginx/html
      - ${HTTP_VOLUME:-/tmp/nginx}/certs:/etc/nginx/certs:rw
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: boilerplatejs_http
      NGINX_DOCKER_GEN_CONTAINER: boilerplatejs_docker_gen
    logging:
      driver: ${SSL_LOG_DRIVER:-json-file}
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE:-2m}
        max-file: ${LOGGING_OPTIONS_MAX_FILE:-10}
    networks:
      boilerplatejs:
        aliases:
          - boilerplatejs_ssl

  boilerplatejs_http:
    image: nginx
    container_name: boilerplatejs_http
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    restart: always
    ports:
      - "${IP:-0.0.0.0}:${HTTP_PORT:-80}:80"
      - "${IP:-0.0.0.0}:${HTTP_PORT:-443}:443"
    volumes:
      - ${HTTP_VOLUME:-/tmp/nginx}/conf.d:/etc/nginx/conf.d
      - ${HTTP_VOLUME:-/tmp/nginx}/vhost.d:/etc/nginx/vhost.d
      - ${HTTP_VOLUME:-/tmp/nginx}/html:/usr/share/nginx/html
      - ${HTTP_VOLUME:-/tmp/nginx}/certs:/etc/nginx/certs:ro
      - ${HTTP_VOLUME:-/tmp/nginx}/htpasswd:/etc/nginx/htpasswd:ro
    logging:
      driver: ${HTTP_LOG_DRIVER:-json-file}
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE:-4m}
        max-file: ${LOGGING_OPTIONS_MAX_FILE:-10}
    networks:
      boilerplatejs:
        aliases:
          - boilerplatejs_http

  boilerplatejs_docker_gen:
    image: jwilder/docker-gen:0.7.3
    container_name: boilerplatejs_docker_gen
    command: -notify-sighup boilerplatejs_http -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    restart: always
    volumes:
      - ${HTTP_VOLUME:-/tmp/nginx}/conf.d:/etc/nginx/conf.d
      - ${HTTP_VOLUME:-/tmp/nginx}/vhost.d:/etc/nginx/vhost.d
      - ${HTTP_VOLUME:-/tmp/nginx}/html:/usr/share/nginx/html
      - ${HTTP_VOLUME:-/tmp/nginx}/certs:/etc/nginx/certs:ro
      - ${HTTP_VOLUME:-/tmp/nginx}/htpasswd:/etc/nginx/htpasswd:ro
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/tmp/docker.sock:ro
      - ./config/http/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    logging:
      driver: ${DOCKER_GEN_LOG_DRIVER:-json-file}
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE:-2m}
        max-file: ${LOGGING_OPTIONS_MAX_FILE:-10}
    networks:
      boilerplatejs:
        aliases:
          - boilerplatejs_docker_gen
